---
- name: Check golang installed
  command: which go
  register: go_installed
  ignore_errors: yes

- name: Create go dir
  become: true
  file:
    path: /opt/go-{{ go.version }}/
    state: directory

- name: Download and unarchive golang
  become: true
  unarchive:
    src: "{{ go.url }}"
    remote_src: yes
    dest: /opt/go-{{ go.version }}/
  when: go_installed.rc != 0

- name: Setup golang environment
  blockinfile:
    path: "~/.bashrc"
    block: |
      export GOROOT=/opt/go-{{ go.version }}/go
      export GOPATH=$HOME/go
      export GO111MODULE=on
      export PATH=$GOPATH/bin:$GOROOT/bin:$PATH

- name: Fix GOPATH owner
  file:
    path: /home/vagrant/go
    owner: vagrant
    group: vagrant
    state: directory
