---
- name: Update apt
  apt:
    update_cache: yes

- name: Install packages
  become: true
  apt:
    name: "{{ item }}"
  loop:
    - build-essential
    - tmux
    - unzip
    - curl
    - wget
    - apache2-utils
    - htop
    - make
    - gcc
    - python-dev
    - python3-dev
