---
- name: Install vim-plug
  shell: "curl -fLo ~/.vim/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim"

- name: Copy vimrc
  template:
      dest: ~/.vimrc
      src: templates/.vimrc
